@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}

# @name create_account
POST {{BASE_URL}}/accounts
Content-Type: application/json

{
  "name": "newuser",
  "password": "securepassword",
  "email": "newuser@mail.com"
}

###

# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "name": "newuser",
  "password": "securepassword",
  "email": "newuser@mail.com"
}

###

# @name create_question
POST {{BASE_URL}}/questions
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

