@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}

# @name create_account
POST {{BASE_URL}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "123456"
}

###

# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "name": "newuser",
  "password": "securepassword",
  "email": "newuser@mail.com"
}

###

# @name create_question
POST {{BASE_URL}}/questions
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "title": "Nova pergunta 2",
  "content" : "Conteúdo da pergunta"
}

###

# @name fetch_recent_questions
GET {{BASE_URL}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}


